# InventorySQL config - by ThisIsAreku - http://dev.bukkit.org/server-mods/inventorysql/
check-interval: 600
after-login-delay: 1
check-plugin-updates: true
no-creative: true
multiworld: true
allow-unsafe-ench: false
mirror-mode: false
use-permissions: false
mysql:
  host: localhost:3306
  user: root
  pass: pass
  db: minecraft
  table-prefix: invsql
  pool-size: 3
backup:
  enabled: true
  cleanup-days: 5
messages:
  no-modif: 'No modifications'
  modif: '%s items added, %s items removed of %s items'
  no-online: 'None of these players were online..'
  check-n-players: 'Checking %s player(s)'
  check-all-players: 'Checking all players...'
  check-yourself: 'Checking yourself...'
  mirror-wait: 'Hello %s ! Wait a little, your inventory is loading..'
  mirror-latest: 'Your inventory is ready !'
  mirror-done: 'Your inventory has been loaded !'
update-events:
  join: true
  quit: true
  changeworld: true
  respawn: true
  bedenter: true
  bedleave: true
  death: true
debug: false